### ISSUE TITLE
underflow encountered in exp

### ISSUE THREAD

**Issue by lucienwb** [theochem/denspart#28]
Hi, I am using the latest denspart to compute the MBIS charge for NaCl+ molecule and I got an underflow floating point error. Could you help me to figure out how to solve it? I have attached the npz input file of my system here.

[density.npz.zip](https://github.com/user-attachments/files/16554937/density.npz.zip)

```
MBIS partitioning --
Building local grids
Integral of density: 27.0000312435445
Optimization
#Iter  #Call         ekld          kld  -constraint     grad.rms  cputime (s)
-----  -----  -----------  -----------  -----------  -----------  -----------
    1      1    0.9464229   -0.0535358   9.9996e-01   2.7860e-01    0.0008520
    2      2    0.9201671    0.2156242   7.0454e-01   4.8488e-01    0.0004890
    3      3    0.5248671   -0.0043593   5.2923e-01   3.0010e-01    0.0003740
    4      4    0.4227335   -0.1046833   5.2742e-01   1.0734e-01    0.0003590
    5      5    0.4141565   -0.1132869   5.2744e-01   9.2535e-02    0.0003790
    6      6    0.3621397   -0.1258460   4.8799e-01   4.7860e-02    0.0005020
    7      6    0.3621397   -0.1258460   4.8799e-01   4.7860e-02    0.0005020
    8      7    0.3476923   -0.0592254   4.0692e-01   3.8484e-02    0.0004180
    9      8    0.3385307    0.0251115   3.1342e-01   3.0207e-02    0.0004790
   10      9    0.3288468    0.1784912   1.5036e-01   1.3023e-02    0.0003790
   11      9    0.3288468    0.1784912   1.5036e-01   1.3023e-02    0.0003790
   12     10    0.3270108    0.2639925   6.3018e-02   5.3819e-03    0.0004440
   13     11    0.3261740    0.3118730   1.4301e-02   4.2858e-03    0.0004120
   14     12    0.3260905    0.3015101   2.4580e-02   3.1220e-03    0.0003650
Traceback (most recent call last):
  File "/chemtools/bin/denspart", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/chemtools/lib/python3.11/site-packages/denspart/__main__.py", line 50, in main
    pro_model, localgrids = optimize_reduce_pro_model(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/denspart/vh.py", line 51, in optimize_reduce_pro_model
    pro_model, localgrids = optimize_pro_model(
                            ^^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/denspart/vh.py", line 153, in optimize_pro_model
    optresult = minimize(
                ^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_minimize.py", line 746, in minimize
    res = _minimize_trustregion_constr(fun, x0, args, jac, hess, hessp,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 528, in _minimize_trustregion_constr
    _, result = tr_interior_point(
                ^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_trustregion_constr/tr_interior_point.py", line 321, in tr_interior_point
    z, state = equality_constrained_sqp(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_trustregion_constr/equality_constrained_sqp.py", line 161, in equality_constrained_sqp
    f_next, b_next = fun_and_constr(x_next)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_trustregion_constr/tr_interior_point.py", line 82, in function_and_constraints
    f = self.fun(x)
        ^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 324, in fun
    self._update_x(x)
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 282, in _update_x
    self._update_hess()
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 315, in _update_hess
    self._update_grad()
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 306, in _update_grad
    self.g = self._wrapped_grad(self.x, f0=self.f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 41, in wrapped
    return np.atleast_1d(grad(np.copy(x), *args))
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 83, in derivative
    self._compute_if_needed(x, *args)
  File "/chemtools/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 73, in _compute_if_needed
    fg = self.fun(x, *args)
         ^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/denspart/vh.py", line 462, in ekld
    pro = pro_model.compute_density(grid, localgrids, cache)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/denspart/vh.py", line 380, in compute_density
    np.add.at(pro, localgrid.indices, fn.compute(localgrid.points, cache))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/denspart/mbis.py", line 98, in compute
    exp = self._compute_exp(exponent, dists, cache)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/denspart/mbis.py", line 86, in _compute_exp
    return compute_cached(
           ^^^^^^^^^^^^^^^
  File "/chemtools/lib/python3.11/site-packages/denspart/cache.py", line 66, in compute_cached
    result = func()
             ^^^^^^
  File "/chemtools/lib/python3.11/site-packages/denspart/mbis.py", line 90, in <lambda>
    func=(lambda: np.exp(-exponent * dists)),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
FloatingPointError: underflow encountered in exp
```

**Comment by tovrstra** [comment]
Thanks for bringing this up. The code currently enables underflow checks for debugging purposes, but they should be harmless in practice. (It just means that we're computing things that are zero, which can probably be dealt with more efficiently.)

**Comment by lucienwb** [comment]
@tovrstra Thank you for your updates, now the calculation shows no error from my side!
